VAX-431: Missing relationId
electric-sql/typescript-client pull request #36
Opened 2022-12-06 15:29 UTC by balegas

Filked relationId on SatTransOp

Also added couple of Int types that I have seen down the wire

2022-12-06 15:43 UTC, define-null requested changes

2022-12-06 18:30 UTC, balegas commented on src/satellite/client.ts
> +              relationId: relation?.id
addressed.

2022-12-06 18:32 UTC, balegas commented
Also closes VAX-432

2022-12-06 21:23 UTC, define-null approved these changes
Looks good to me. We need to make sure, we do not close VAX-431, VAX-432 without providing corresponding integration tests in Electric repo.

2022-12-07 23:00 UTC, merged

2022-12-07 23:02 UTC, balegas commented
Keeping tickets opens